### Get local host
GET http://localhost:3000/

### Get local songs
GET http://localhost:3000/songs

### Get local songs with pagination
GET http://localhost:3000/songs?page=1&limit=2

### Create local song
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Rap'",
  "artists": [3,2],
  "album": "Rich Mafia",
  "releaseDate": "2024-10-25",
  "genre": "Pop",
  "duration": "02:00"
}


### Get local song by id
GET http://localhost:3000/songs/2


### Update local song by id
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
  "title": "Let it go "
}

### Delete local song by id
DELETE http://localhost:3000/songs/1


### Create local playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "My favorite songs",
  "description": "A playlist of my favorite songs",
  "songs": [3,23],
  "user": 1
}