### Get local host
GET http://localhost:3000/

### Get local songs
GET http://localhost:3000/songs

### Get local songs with pagination
GET http://localhost:3000/songs?page=1&limit=2

### Create local song
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlJpY2hAdmFnb3MuY29tIiwidXNlcklkIjo0LCJpYXQiOjE3MzY4MTAzMDksImV4cCI6MTczNjg5NjcwOX0.3PwZ29NKxybodpFfi7bXW3tmY1zZbRU9-LtchJYDNII

{
  "title": "Rap'",
  "artists": [1],
  "album": "Rich Mafia",
  "releaseDate": "2024-10-25",
  "genre": "Pop",
  "duration": "02:00"
}


### Get local song by id
GET http://localhost:3000/songs/2


### Update local song by id
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
  "title": "Let it go "
}

### Delete local song by id
DELETE http://localhost:3000/songs/1


### Create local playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "My favorite songs",
  "description": "A playlist of my favorite songs",
  "songs": [3,23],
  "user": 1
}

### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "toonchavez",
  "firstName": "Miguel",
  "email": "toonchavez@gmail.com",
  "password": "123456",
  "bio": "Test user"
}


### Sign up new Artist
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "GeraMx",
  "firstName": "Gera",
  "email": "Rich@vagos.com",
  "password": "123456",
  "bio": "Test user"
}
### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "toonchavez@gmail.com",
  "password": "123456"
}

### Login Artist  
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "Rich@vagos.com",
  "password": "123456"
}

## Access TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvb25jaGF2ZXpAZ21haWwuY29tIiwidXNlcklkIjoyLCJpYXQiOjE3MzY4MTAyODcsImV4cCI6MTczNjg5NjY4N30.SKvkVYEUsnuKUCeNfrwsdAVn9TeG-RcY2rpeCZ4vJdE"

### Get Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlJpY2hAdmFnb3MuY29tIiwidXNlcklkIjo0LCJpYXQiOjE3MzY4MTAzMDksImV4cCI6MTczNjg5NjcwOX0.3PwZ29NKxybodpFfi7bXW3tmY1zZbRU9-LtchJYDNII